# Generated by Django 4.2.16 on 2024-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menuitem_created_on_menuitem_updated_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.FileField(blank=True, null=True, unique=True, upload_to=''),
        ),
    ]
